export const categories = [
  { id: 1, title: "意識・心構え", slug: "mindset", en: "Awareness/attitude" },
  {
    id: 2,
    title: "面接対応時",
    slug: "interviewing",
    en: "At the time of interview",
  },
  {
    id: 3,
    title: "体験入店時",
    slug: "trial",
    en: "When entering the trial store",
  },
  {
    id: 4,
    title: "出退勤時",
    slug: "attendance",
    en: "At the time of arrival and departure",
  },
  { id: 5, title: "電話応対", slug: "phone", en: "Telephone answering" },
  { id: 6, title: "予約連絡", slug: "booking", en: "Reservation contact" },
  { id: 7, title: "準備・待機中", slug: "preparing", en: "Preparing/Waiting" },
  {
    id: 8,
    title: "送迎中",
    slug: "transporting",
    en: "Picking up and dropping off",
  },
  {
    id: 9,
    title: "接客トラブル",
    slug: "service",
    en: "Customer service trouble",
  },
  {
    id: 10,
    title: "女性間トラブル",
    slug: "interpersonal",
    en: "trouble between women",
  },
  { id: 11, title: "事務所トラブル", slug: "office", en: "office troubles" },
  { id: 12, title: "SNS運用", slug: "social", en: "SNS operation" },
  { id: 13, title: "媒体管理", slug: "media", en: "media management" },
  { id: 14, title: "退店時", slug: "exiting", en: "When leaving the store" },
  {
    id: 15,
    title: "言葉遣い・コミュニケーション",
    slug: "communication",
    en: "Language/communication",
  },
  {
    id: 16,
    title: "法令・コンプライアンス",
    slug: "compliance",
    en: "Laws and compliance",
  },
  { id: 17, title: "その他", slug: "Miscellaneous", en: "others" },
];
